### ISSUE TITLE
[BUG] Sidebar Graphical Tweaks

### ISSUE THREAD

**Issue by phillux** [LasticXYZ/LasticUI#106]
**Describe the bug**
There are some alignment and text issues in the sidebar. These are all very easy fixes.

**To Reproduce**

1. Go to 'test.lastic.xyz/bulkcore1'
2. View sidebar

**Child issues**
- [x] #107 
- [x] #108
- [x] #109
- [x] #110

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by poppyseedDev** [comment]
All these issues can be resolved in a single PR. When you submit a PR just mention in the PR, which issues it closes.
