### ISSUE TITLE
"My Cores" page improvements

### ISSUE THREAD

**Issue by phillux** [LasticXYZ/LasticUI#111]
**Is your feature request related to a problem? Please describe.**
There are three categories of cores that are all mixed together and not sorted properly. We need a way for users to better manage their active and assigned cores, while disregarding or downplaying expired cores.

**Describe the solution you'd like**
We need three sections in the "My Cores" page.

- Unassigned Cores
  - Unassigned Active Cores
- Assigned Cores
  - Assigned Active Cores
- Expired Cores

**Additional context**
There is room in this issue for discussion and I encourage that. 

For example, Assigned cores disappear from the UI. This is problematic for obvious reasons. But sometimes users may want to assign cores to tasks that are NOT theirs, yet is the ability to manipulate cores (splitting) after assignment possible? Or can a user "unassign" a core assigned to task?

There are also ways we can improve the UI on this page to show the time better rather than RegionIDs which are opaque to the user. We should AT LEAST have block numbers, but preferrably do things always based on date and time, ideally grabbing the user's timezone from their browser.

Also, the cores are sorted arbitrarily. We need proper groupings, AND in-group sorting that makes sense, not necessarily customizable by the user.

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by poppyseedDev** [comment]
Mentioned in issue #105
