### ISSUE TITLE
change env file name in Readme.

### ISSUE THREAD

**Issue by jeevikasirwani** [LasticXYZ/LasticUI#115]
In readme file in getting started section "Copy the .env.local.example and rename it to .env.local. If you are using Subscan create a subscan public token and add it here: NEXT_PUBLIC_SUBSCAN_TOKEN='...'.  Set up the environmental variables, copy and rename .env.local.example.",                                                                                                                                                                       ".env.local.example" file is mentioned                                                                                                                                                                              while in the project directory it is named as ".env.local.copy.example"
so for development the reference is ".env.local.copy.example" 
**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by poppyseedDev** [comment]
Thanks for the issue, the file seems to be wrongly renamed at some point.
