### ISSUE TITLE
[BUG] Unable to select wallet in modal when large mount of accounts from Polkadot Extension

### ISSUE THREAD

**Issue by ltfschoen** [LasticXYZ/LasticUI#123]
**Describe the bug**

If I have a lot of accounts in Polkadot.js Extension, then when I click to choose or change the current account, it doesn't let me scroll up or down the list, so I can only see the middle of the list. If I zoom fully out and expand the screen I can still only see about ~50 accounts.

**To Reproduce**

1. Go to https://test.lastic.xyz/instacore
2. Click on Connect Wallet
3. Select Polkadot.js (where >100 accounts have been imported and are visible)
4. Try to scroll up and down to choose a different account or disconnect the current account

**Expected behavior**
It should show the top of the list first and allow you to scroll down to the end of the list, instead of preventing scrolling all together

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOs 14.1.1
- Browser [e.g. chrome, safari] Brave
- Version [e.g. 22] [Version 1.63.169 Chromium: 122.0.6261.111 (Official Build) (arm64)](https://brave.com/latest/)

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by ltfschoen** [comment]
✋

**Comment by ltfschoen** [comment]
@poppyseedDev If you provide mentoring or guidance on how you would go about solving it I could try and update this PR and do it for you https://github.com/LasticXYZ/LasticUI/pull/124

**Comment by poppyseedDev** [comment]
Hei @ltfschoen I did a quick merge, it's quite a small issue, so the fix was easier to just code up rather than to explain, could you please check the deployment if it fixes your issue?
