### ISSUE TITLE
Implementing teleport between Kusama Relay chain and Kusama Coretime chain

### ISSUE THREAD

**Issue by poppyseedDev** [LasticXYZ/LasticUI#136]
Dependent on release of Coretime Kusama

**Comment by phillux** [comment]
@poppyseedDev coretime chain is live on kusama
<img width="321" alt="image" src="https://github.com/LasticXYZ/LasticUI/assets/6450379/1c7d06f1-dbe0-407b-babd-4bcd154c30d9">
