### ISSUE TITLE
[BUG] Too much spacing in the scrolling partners header

### ISSUE THREAD

**Issue by phillux** [LasticXYZ/LasticUI#139]
**Describe the bug**
Too much spacing in the scrolling partners header

**Expected behavior**
The spacing should be black and extending the coloring above the "for traders" text". Instead, it's extending downward from the dark blue part of the scrolling partners.

**Screenshots**
<img width="292" alt="image" src="https://github.com/LasticXYZ/LasticUI/assets/6450379/cf21e108-d9a7-4ebd-840e-975d7904e70b">

**Comment by poppyseedDev** [comment]
is this mobile?

**Comment by phillux** [comment]
> is this mobile?

desktop. probably only visible on OLED screens. firefox
