### ISSUE TITLE
[BUG] Transaction Failed: Error: Assertion failed

### ISSUE THREAD

**Issue by ltfschoen** [LasticXYZ/LasticUI#150]
**Describe the bug**
If I try to purchase credits at http://localhost:3005/instacore using 10 ROC with "Auto Teleport" off so I can afford it it gives error `Transaction Failed: Error: Assertion failed` in the UI when I click Purchase 

**To Reproduce**

1. Run locally
2. Click to purchase
3. View error

**Expected behavior**
No error should occur

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS 14.1.1
- Browser [e.g. chrome, safari] Chrome 
- Version [e.g. 22] Version 123.0.6312.124 (Official Build) (arm64)

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by poppyseedDev** [comment]
this was already fixed
