### ISSUE TITLE
[BUG] Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33

### ISSUE THREAD

**Issue by ltfschoen** [LasticXYZ/LasticUI#157]
**Describe the bug**
If I connect with Polkadot.js Extension and one of the accounts is an EVM account (i.e. 0x____) instead of a Substrate SS58 address then it crashes with browse console error `Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33` unless I know to hide that specific address within Polkadot.js Extension

**To Reproduce**

1. Import an EVM address (e.g. for Moonbeam) into Polkadot.js Extension and don't hide it
2. Click Connect Wallet
3. Click Polkadot.js

**Expected behavior**
It should try/catch and ignore that EVM wallet instead of crashing

**Screenshots**

![Uploading Screenshot 2024-04-19 at 6.42.28 pm.png…]()

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS 14.1.1
- Browser [e.g. chrome, safari] Brave
- Version [e.g. 22] latest version

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by ltfschoen** [comment]
Oh, i just realised that i'd created this same issue before here https://github.com/LasticXYZ/LasticUI/issues/69

Is this an appropriate temporary solution?

**Comment by poppyseedDev** [comment]
@vikiival

**Comment by poppyseedDev** [comment]
@ltfschoen could you provide more info on can you import an EVM address (e.g. for Moonbeam) into Polkadot.js Extension?

**Comment by ltfschoen** [comment]
> @ltfschoen could you provide more info on can you import an EVM address (e.g. for Moonbeam) into Polkadot.js Extension?

yes, it is possible to import an EVM address that you use across multiple EVM chain accounts, such as Moonbeam, Ethereum, etc.

**Comment by ltfschoen** [comment]
Rehashed issues:

- https://github.com/polkadot-js/extension/issues/1250#issuecomment-1931926244
- https://github.com/kodadot/nft-gallery/issues/9412
- https://github.com/zeitgeistpm/ui/issues/2185#event-11773056586
- https://grillapp.net/@luke/polkadot-d-app-errors-when-handling-accounts-supplied-by-the-47114
- https://github.com/Joystream/pioneer/issues/4782

Example solutions:
- https://github.com/dappforce/polkaverse/pull/210/files#diff-ca62a13994aae3c545ad2d796d272f3ee8c0ab33b83bb3d5c023dc553b55f984R14
- https://github.com/zeitgeistpm/ui/pull/2236

**Comment by poppyseedDev** [comment]
> > @ltfschoen could you provide more info on can you import an EVM address (e.g. for Moonbeam) into Polkadot.js Extension?
> 
> yes, it is possible to import an EVM address that you use across multiple EVM chain accounts, such as Moonbeam, Ethereum, etc.

Sent video of how this would work.

**Comment by ltfschoen** [comment]
> > > @ltfschoen could you provide more info on can you import an EVM address (e.g. for Moonbeam) into Polkadot.js Extension?
> > 
> > 
> > yes, it is possible to import an EVM address that you use across multiple EVM chain accounts, such as Moonbeam, Ethereum, etc.
> 
> Hei @ltfschoen could you send a video of how to import this account into polkadot js.

it shows how to do it at 2 mins into this video (I'm not the presenter) https://youtu.be/9ohp8k4Hz8c?feature=shared

the videos are published in the wiki https://guide.kusama.network/docs/learn-guides-accounts/

**Comment by poppyseedDev** [comment]
Nice thanks @vikiival! Okay, let's then fix this.
