### ISSUE TITLE
[BUG] Can assign a core to a non-existent ParaID

### ISSUE THREAD

**Issue by phillux** [LasticXYZ/LasticUI#160]
**Describe the bug**
I assigned an interlaced core to paraID 8888 on Rococo, although there is no such registered paraID 

**To Reproduce**

1. Go to 'My Cores'
2. Click on any active core
3. Scroll down to 'Assign' 
4. Enter a non-registered paraID
5. "Successful" transaction occurs

**Expected behavior**
Ideally, this should not be allowed to occur. We should see an error that says the Parathread does is not registered, along with information on how to do so. At the very least, there should be an error message saying that the core was assigned incorrectly.

**Screenshots**
<img width="656" alt="image" src="https://github.com/LasticXYZ/LasticUI/assets/6450379/80f1d61e-2121-4fa5-bda9-af8d892b1787">

**Desktop (please complete the following information):**

- OS:Mac OS
- Browser Firefox

**Comment by poppyseedDev** [comment]
But this is not really our problem...
