### ISSUE TITLE
Change the pricing curve based on the new code in the broker pallet

### ISSUE THREAD

**Issue by poppyseedDev** [LasticXYZ/LasticUI#189]
There has been a major change in the implementation of the broker pallet - see [link](https://github.com/paritytech/polkadot-sdk/blob/eca1052ea1eddeede91da8f9f7452ea8b57e7942/substrate/frame/broker/src/adapt_price.rs#L109-L117)

this change hasn't been yet implemented yet on Kusama, but should be already active on Rococo. You can help yourself with looking at the following graph while implementing it.
<img width="1250" alt="Screenshot 2024-06-13 at 20 37 50" src="https://github.com/LasticXYZ/LasticUI/assets/30662672/0d599092-7d1d-416f-9ddf-f36b65375bfa">

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by tien** [comment]
Taking a look now ✋
