### ISSUE TITLE
Backend: How to fetch, store, and present data

### ISSUE THREAD

**Issue by phillux** [LasticXYZ/LasticUI#2]
# Introduction

We want to keep Lastic UI agile and cost-efficient, and using RPC or Extrinsic calls may be the best way to do that. This may have the cost of being a little slow depending on the RPC provider. Also, we may need to record, store and index historical data so that the Marketplace participants can make informed decisions. 

Ideally, we should be utilizing as much web3 infrastructure as possible to keep the frontend as lean as possible, which also aligns with Polkadot's and Lastic's values. This would help us not only gain support from the community with regards to image and potential treasury funding, but also potentially reduce the workload the Lastic team by leveraging eager participants to collaborate. 

# Discussion 
How should we best gather, record, store and index the data?

**Comment by poppyseedDev** [comment]
A note from @vikiival: it is much more efficient to use SubSquid with querying first events and then extrinsics. Don't query storage because that's a pricy operation.
