### ISSUE TITLE
Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33

### ISSUE THREAD

**Issue by ltfschoen** [LasticXYZ/LasticUI#69]
If I try to buy coretime when I connect a wallet using Polkadot.js Extension it crashes with the error shown in the below screenshot.

I get this error using the latest Brave browser [Version 1.63.162 Chromium: 122.0.6261.69 (Official Build) (arm64)](https://brave.com/latest/), but not with Chrome

This is a common error that I posted about here https://polkaverse.com/@luke/polkadot-d-app-errors-when-handling-accounts-supplied-by-the-47114 and various solutions have been mentioned there like wrapping in try/catch.

I just finally figured out the cause. It is because I have multiple accounts imported into Polkadot.js Extension, including both Substrate SS58 addresses (5.....) and EVM addresses (i.e. 0x....).

If I make the visibility of all my accounts invisible, and then click the Connect Wallet button, and then click Polkadot.js button, then it will crash with the below error if any of the EVM accounts are visible (e.g. a Moonbeam account)

<img width="1325" alt="Screenshot 2024-03-03 at 6 33 40 pm" src="https://github.com/LasticXYZ/LasticUI/assets/6226175/3956fa2c-4729-4f69-8784-29be349c47f5">

**Comment by poppyseedDev** [comment]
Thanks for the issue. We will look into it, I actually had a similar error before, but never got to resolving it.

**Comment by poppyseedDev** [comment]
This issue has to be fixed on https://github.com/lasticXYZ/lastic-sdk
