### ISSUE TITLE
Para Id create button

### ISSUE THREAD

**Issue by poppyseedDev** [LasticXYZ/LasticUI#77]
Implement this button along with a modal ->

Help yourself with how its implemented in polkadot js:
https://github.com/polkadot-js/apps/blob/master/packages/page-parachains/src/Parathreads/RegisterId.tsx

Concept design:
<img width="793" alt="Screenshot 2024-03-24 at 11 48 10" src="https://github.com/LasticXYZ/LasticUI/assets/30662672/80779d2c-ae64-4103-8088-f6c85d1011a5">

Polkadot js:
https://polkadot.js.org/apps/#/parachains/parathreads
<img width="1134" alt="Screenshot 2024-03-24 at 11 38 33" src="https://github.com/LasticXYZ/LasticUI/assets/30662672/724008b8-2ccf-4921-bce4-d9c2307f3e2f">

<img width="1511" alt="Screenshot 2024-03-24 at 11 38 06" src="https://github.com/LasticXYZ/LasticUI/assets/30662672/4ac06e00-28ee-4450-ba14-6cf9c22cddea">

**Comment by poppyseedDev** [comment]
**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by poppyseedDev** [comment]
A sample of how a Create Para Id modal should look like: (note the design is not so important as is functionality)

<img width="721" alt="Screenshot 2024-03-26 at 13 40 57" src="https://github.com/LasticXYZ/LasticUI/assets/30662672/bcf3b243-c90d-436a-aae9-fbff46fec8b9">

**Comment by Nith567** [comment]
✋ I am intrested to work on this issue, i can't find text PARA IDS, can give me the location also i assume its in main branch

**Comment by poppyseedDev** [comment]
Sure: https://test.lastic.xyz/paraId
