### ISSUE TITLE
create crowdfunding smart contract - deploy on Moonbeam

### ISSUE THREAD

**Issue by poppyseedDev** [LasticXYZ/LasticUI#84]
Deploy the contracts: https://github.com/LasticXYZ/ext-contracts

Create solidity smart contracts that will make it possible for people to crowdfunding their core purchase.

**Comment by poppyseedDev** [comment]
**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by noahjoeris** [comment]
✋

**Comment by noahjoeris** [comment]
Solved via PR [here](https://github.com/LasticXYZ/ext-contracts/pull/1#issue-2245992459)
