### ISSUE TITLE
[BUG] Incorrect marking of sale end period

### ISSUE THREAD

**Issue by poppyseedDev** [LasticXYZ/LasticUI#94]
**Describe the bug**
It says sale ended but it actually hasn't.

**To Reproduce**
Unfortunately this bug is harder to reproduce, since you have to wait for the exact time when the stable price ends. 
At that time it's still possible to buy a core, that is why the Sale end has been calculated wrongly.

1. Go to https://test.lastic.xyz/bulkcore1
2. Check screenshot

**Expected behavior**

**Screenshots**
<img width="1302" alt="Screenshot 2024-03-25 at 11 37 00" src="https://github.com/LasticXYZ/LasticUI/assets/30662672/6780d045-b7b6-4e28-9157-9cbab58e34a0">

**Additional context**
For a bit more context:
https://github.com/LasticXYZ/LasticUI/pull/101/files#r1540892616

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by daiagi** [comment]
:wave:

**Comment by poppyseedDev** [comment]
https://github.com/LasticXYZ/LasticUI/pull/101/files#r1540892616

**Comment by poppyseedDev** [comment]
@daiagi I looked into this issue, it's really ugly bug more from Rococo side, then ours. I suggest you check other issues.
