### ISSUE TITLE
Implement auto teleport

### ISSUE THREAD

**Issue by poppyseedDev** [LasticXYZ/LasticUI#97]
Teleport is already implemented, so you can help yourself with the necessary functions that are implemented there:
<img width="1504" alt="Screenshot 2024-03-26 at 14 48 04" src="https://github.com/LasticXYZ/LasticUI/assets/30662672/ae158f68-ec60-4aeb-b9ac-f01b9224eac1">
 
The idea is that if the user doesn't have enough funds on the coretime chain it checks the rococo relay chain if the user has enough funds there it automatically teleports the funds from the relay chain to the coretime chain and afterwards executes the transaction.

Add this feature to every transaction.

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by noahjoeris** [comment]
✋

**Comment by Nith567** [comment]
What i understood is when assests moving from A-B if we dont have enough funds in A then we move from B-A then again A-B is that what u mean exactly

**Comment by poppyseedDev** [comment]
> What i understood is when assests moving from A-B if we dont have enough funds in A then we move from B-A then again A-B is that what u mean exactly

When a person doesn't have money on the coretime chain it checks if he has money on the relay chain and does auto teleport from relay chain to the coretime chain and then submits the transaction. So the person just needs to do click click and that's it should be a very nice UX for newcommers in the Polkadot ecosystem.
