### ISSUE TITLE
[BUG] Add a vertical scroll bar to the sidebar

### ISSUE THREAD

**Issue by poppyseedDev** [LasticXYZ/LasticUI#98]
**Describe the bug**
On smaller screens you are unable to see the entire sidebar. A quick solution is to add a scroll bar so that people can see the entirety of the contents of the sidebar.

**To Reproduce**

1. Go to any page in the main app
2. Check the sidebar

**Screenshots**

<img width="252" alt="Screenshot 2024-03-27 at 07 20 29" src="https://github.com/LasticXYZ/LasticUI/assets/30662672/c1edab02-2d11-43c7-b6cb-a7b97285808f">

**Desktop (please complete the following information):**
On a normal laptop desktop, you are unable to see the whole scroll bar.
- Browser - chrome

**Additional context**

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

**Comment by daiagi** [comment]
:wave:
